nav:
  - Главная:
    - Главная: index.md
    - Развёртывание GitHub Pages: root/CI.md
    - Мой плагин на Python для MkDocs: root/yml_plugin.md
  - Python:
    - Python: Python/index.md
    - Возможности языка:
      - Строки: Python/strings.md
      - Списки: Python/lists.md
      - Файлы: Python/files.md
      - Декораторы: Python/Decorators.md
      - Методы классов: Python/Class_methods.md
      - Дандер методы: Python/Dander.md
      - Asyncio: Python/Asyncio.md
      - Regex: Python/Regex.md
    - Пакеты:
      - Создание venv: Python/venv.md
      - uv: Python/uv.md
      - Poetry: Python/poetry.md
      - Black: Python/black.md
      - Ruff: Python/ruff.md
    - Фишки: 
      - CLI: Python/CLI.md
      - 60th: Python/60th.md
      - Zen of Python: Python/Zen.md
  - FastAPI:
    - FastAPI: FastAPI/index.md
    - Веб-сокеты: FastAPI/WebSockets.md
    - Pydantic: FastAPI/Pydantic.md
    - SQLAlchemy: FastAPI/SQLAlchemy.md
  - Docker: Docker/index.md
  - Vue.js: Vue.js/index.md
  - Bash: 
    - Bash: Bash/index.md
    - CLI команды: Bash/CLI.md
  - SQL:
    - SQL: SQL/index.md
  - Git:
    - Git: Git/index.md
    - Ветки: Git/branches.md



site_name: Utils Docs
site_url: https://PurpleSwtr.github.io/Utils-Docs/

repo_url: https://github.com/PurpleSwtr/Utils-Docs
repo_name: PurpleSwtr/Utils-Docs

theme:
  name: material
  text: Inter
  code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tooltips
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/purpleswtr
      name: Мой Telegram
    - icon: fontawesome/brands/github 
      link: https://github.com/PurpleSwtr
      name: Мой GitHub

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true


extra_css:
  - stylesheets/extra.css